# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/rtcs_system/rtcs_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system || ORIG_REF_NAME==rtcs_system}]

# IP: bd/rtcs_system/ip/rtcs_system_processing_system7_0_0/rtcs_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_processing_system7_0_0 || ORIG_REF_NAME==rtcs_system_processing_system7_0_0}]

# IP: bd/rtcs_system/ip/rtcs_system_axi_gpio_0_0/rtcs_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_axi_gpio_0_0 || ORIG_REF_NAME==rtcs_system_axi_gpio_0_0}]

# IP: bd/rtcs_system/ip/rtcs_system_processing_system7_0_axi_periph_0/rtcs_system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==rtcs_system_processing_system7_0_axi_periph_0}]

# IP: bd/rtcs_system/ip/rtcs_system_rst_processing_system7_0_100M_0/rtcs_system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==rtcs_system_rst_processing_system7_0_100M_0}]

# IP: bd/rtcs_system/ip/rtcs_system_axi_gpio_0_1/rtcs_system_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_axi_gpio_0_1 || ORIG_REF_NAME==rtcs_system_axi_gpio_0_1}]

# IP: bd/rtcs_system/ip/rtcs_system_xbar_0/rtcs_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_xbar_0 || ORIG_REF_NAME==rtcs_system_xbar_0}]

# IP: bd/rtcs_system/ip/rtcs_system_axi_timer_0_0/rtcs_system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_axi_timer_0_0 || ORIG_REF_NAME==rtcs_system_axi_timer_0_0}]

# IP: bd/rtcs_system/ip/rtcs_system_xlconcat_0_0/rtcs_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_xlconcat_0_0 || ORIG_REF_NAME==rtcs_system_xlconcat_0_0}]

# IP: bd/rtcs_system/ip/rtcs_system_auto_pc_0/rtcs_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_auto_pc_0 || ORIG_REF_NAME==rtcs_system_auto_pc_0}]

# XDC: bd/rtcs_system/ip/rtcs_system_processing_system7_0_0/rtcs_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rtcs_system_processing_system7_0_0 || ORIG_REF_NAME==rtcs_system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/rtcs_system/ip/rtcs_system_axi_gpio_0_0/rtcs_system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rtcs_system_axi_gpio_0_0 || ORIG_REF_NAME==rtcs_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/rtcs_system/ip/rtcs_system_axi_gpio_0_0/rtcs_system_axi_gpio_0_0_ooc.xdc

# XDC: bd/rtcs_system/ip/rtcs_system_axi_gpio_0_0/rtcs_system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rtcs_system_axi_gpio_0_0 || ORIG_REF_NAME==rtcs_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/rtcs_system/ip/rtcs_system_rst_processing_system7_0_100M_0/rtcs_system_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==rtcs_system_rst_processing_system7_0_100M_0}]

# XDC: bd/rtcs_system/ip/rtcs_system_rst_processing_system7_0_100M_0/rtcs_system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==rtcs_system_rst_processing_system7_0_100M_0}]

# XDC: bd/rtcs_system/ip/rtcs_system_rst_processing_system7_0_100M_0/rtcs_system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/rtcs_system/ip/rtcs_system_axi_gpio_0_1/rtcs_system_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rtcs_system_axi_gpio_0_1 || ORIG_REF_NAME==rtcs_system_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/rtcs_system/ip/rtcs_system_axi_gpio_0_1/rtcs_system_axi_gpio_0_1_ooc.xdc

# XDC: bd/rtcs_system/ip/rtcs_system_axi_gpio_0_1/rtcs_system_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rtcs_system_axi_gpio_0_1 || ORIG_REF_NAME==rtcs_system_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/rtcs_system/ip/rtcs_system_xbar_0/rtcs_system_xbar_0_ooc.xdc

# XDC: bd/rtcs_system/ip/rtcs_system_axi_timer_0_0/rtcs_system_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtcs_system_axi_timer_0_0 || ORIG_REF_NAME==rtcs_system_axi_timer_0_0}]

# XDC: bd/rtcs_system/ip/rtcs_system_axi_timer_0_0/rtcs_system_axi_timer_0_0_ooc.xdc

# XDC: bd/rtcs_system/ip/rtcs_system_auto_pc_0/rtcs_system_auto_pc_0_ooc.xdc

# XDC: bd/rtcs_system/rtcs_system_ooc.xdc
