set_property PACKAGE_PIN V13 [get_ports {gpio_rtl_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[1]}]
set_property PACKAGE_PIN U17 [get_ports {gpio_rtl_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[0]}]
set_property PACKAGE_PIN V12 [get_ports {pwm_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[0]}]
set_property PACKAGE_PIN W16 [get_ports {timing_outpin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {timing_outpin[0]}]
