# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-5434-Lenovo-G580/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl
    /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog
  } {
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_aw_atc.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_b_atc.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_w_atc.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_atc.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ip/rtcs_system_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ip/rtcs_system_processing_system7_0_0/synth/rtcs_system_processing_system7_0_0.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_and.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_or.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_si_transactor.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_splitter.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_router.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ip/rtcs_system_xbar_0/synth/rtcs_system_xbar_0.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ip/rtcs_system_auto_pc_0/synth/rtcs_system_auto_pc_0.v
    }
      rt::read_vhdl -lib axi_lite_ipif_v3_0_3 {
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_lite_ipif_v3_0/hdl/src/vhdl/ipif_pkg.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_lite_ipif_v3_0/hdl/src/vhdl/pselect_f.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_lite_ipif_v3_0/hdl/src/vhdl/address_decoder.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_lite_ipif_v3_0/hdl/src/vhdl/axi_lite_ipif.vhd
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/lib_cdc_v1_0/hdl/src/vhdl/cdc_sync.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_3 /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/interrupt_control_v3_1/hdl/src/vhdl/interrupt_control.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_9 {
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_gpio_v2_0/hdl/src/vhdl/gpio_core.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_gpio_v2_0/hdl/src/vhdl/axi_gpio.vhd
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ip/rtcs_system_axi_gpio_0_0/synth/rtcs_system_axi_gpio_0_0.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ip/rtcs_system_rst_processing_system7_0_100M_0/synth/rtcs_system_rst_processing_system7_0_100M_0.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/hdl/rtcs_system.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ip/rtcs_system_axi_gpio_0_1/synth/rtcs_system_axi_gpio_0_1.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ip/rtcs_system_axi_timer_0_0/synth/rtcs_system_axi_timer_0_0.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/xlconcat_v2_1/xlconcat.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ip/rtcs_system_xlconcat_0_0/synth/rtcs_system_xlconcat_0_0.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/hdl/rtcs_system_wrapper.vhd
    }
      rt::read_vhdl -lib proc_sys_reset_v5_0_8 {
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/upcnt_n.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/sequence_psr.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/lpf.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/proc_sys_reset.vhd
    }
      rt::read_vhdl -lib blk_mem_gen_v8_3_1 {
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/blk_mem_gen_v8_3/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/blk_mem_gen_v8_3/hdl/blk_mem_gen_v8_3.vhd
    }
      rt::read_vhdl -lib fifo_generator_v13_0_1 {
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/fifo_generator_v13_0/hdl/fifo_generator_v13_0_vhsyn_rfs.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/fifo_generator_v13_0/hdl/fifo_generator_v13_0.vhd
    }
      rt::read_vhdl -lib lib_pkg_v1_0_2 /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/lib_pkg_v1_0/hdl/src/vhdl/lib_pkg.vhd
      rt::read_vhdl -lib axi_timer_v2_0_9 {
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_timer_v2_0/hdl/src/vhdl/counter_f.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_timer_v2_0/hdl/src/vhdl/mux_onehot_f.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_timer_v2_0/hdl/src/vhdl/tc_types.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_timer_v2_0/hdl/src/vhdl/timer_control.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_timer_v2_0/hdl/src/vhdl/count_module.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_timer_v2_0/hdl/src/vhdl/tc_core.vhd
      /home/thomas/Documents/Git/Electronics/EMB/rtcs/rtcs/rtcs.srcs/sources_1/bd/rtcs_system/ipshared/xilinx.com/axi_timer_v2_0/hdl/src/vhdl/axi_timer.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top rtcs_system_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-5434-Lenovo-G580/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  if { [info exists rt::helper_shm_key] && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $rt::helper_shm_key
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
